def privet():
    print("privet")

privet(12)
privet()
privet()
print("что-то добавим")
print("черная пятнца")
pritn("изминения в мастер")
pritn("изминения в мастер")
pritn("изминения в мастер")
privet(12)
privet()
privet()
print("что-то добавим")
print("черная пятнца")
pritn("изминения в мастер")
pritn("изминения в мастер")
pritn("изминения в мастер")
privet(12)
privet()
privet()
print("что-то добавим")
print("черная пятнца")
pritn("изминения в мастер")
pritn("изминения в мастер")
pritn("изминения в мастер")